package tn.edu.esprit.cinfo2.zanga.goldenCage.domain.beans;

// default package
// Generated 5 juil. 2014 01:19:53 by Hibernate Tools 3.4.0.CR1

/**
 * CartItem generated by hbm2java
 */
public class CartItem implements java.io.Serializable {

	private Integer id;
	private int idCart;
	private int idService;

	public CartItem() {
	}

	public CartItem(int idCart, int idService) {
		this.idCart = idCart;
		this.idService = idService;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdCart() {
		return this.idCart;
	}

	public void setIdCart(int idCart) {
		this.idCart = idCart;
	}

	public int getIdService() {
		return this.idService;
	}

	public void setIdService(int idService) {
		this.idService = idService;
	}

}
