package tn.edu.esprit.cinfo2.zanga.goldenCage.domain.beans;

// default package
// Generated 5 juil. 2014 01:19:53 by Hibernate Tools 3.4.0.CR1

/**
 * Itemtodolist generated by hbm2java
 */
public class Itemtodolist implements java.io.Serializable {

	private Integer id;
	private int idTodolist;
	private String state;
	private int idCategory;

	public Itemtodolist() {
	}

	public Itemtodolist(int idTodolist, String state, int idCategory) {
		this.idTodolist = idTodolist;
		this.state = state;
		this.idCategory = idCategory;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdTodolist() {
		return this.idTodolist;
	}

	public void setIdTodolist(int idTodolist) {
		this.idTodolist = idTodolist;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public int getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(int idCategory) {
		this.idCategory = idCategory;
	}

}
